// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.2
// source: open/v1/open.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpenClient is the client API for Open service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type openClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenClient(cc grpc.ClientConnInterface) OpenClient {
	return &openClient{cc}
}

func (c *openClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/api.open.v1.Open/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenServer is the server API for Open service.
// All implementations must embed UnimplementedOpenServer
// for forward compatibility
type OpenServer interface {
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedOpenServer()
}

// UnimplementedOpenServer must be embedded to have forward compatible implementations.
type UnimplementedOpenServer struct {
}

func (UnimplementedOpenServer) Hello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedOpenServer) mustEmbedUnimplementedOpenServer() {}

// UnsafeOpenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenServer will
// result in compilation errors.
type UnsafeOpenServer interface {
	mustEmbedUnimplementedOpenServer()
}

func RegisterOpenServer(s grpc.ServiceRegistrar, srv OpenServer) {
	s.RegisterService(&Open_ServiceDesc, srv)
}

func _Open_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.open.v1.Open/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Open_ServiceDesc is the grpc.ServiceDesc for Open service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Open_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.open.v1.Open",
	HandlerType: (*OpenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Open_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "open/v1/open.proto",
}
